# Generated by Django 4.0 on 2021-12-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
